apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-volume
  labels:
    type: local
spec:
  storageClassName: airflowdags
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "dags"