apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv-2
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/airflow/logs"
--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc-2
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi