apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-volmount-5
  namespace: airflow-k8-local
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /run/desktop/mnt/host/wsl/home/anomp/dev/kube-local/airflow-kube-local/dags
    