apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-local-dags-folder-2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi