apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-01
  namespace: airflow-k8-local
  labels:
    app: airflow-logs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath
  resources:
    requests:
      storage: 10Gi



# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: airflow-logs-pv-3
#   labels:
#     type: local
# spec:
#   storageClassName: hostpath
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: "/opt/airflow/logs"
# --- 

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: airflow-logs-pvc-3
# spec:
#   storageClassName: hostpath
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 5Gi