apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-volmount-5
  namespace: airflow-k8-local  
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

