apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-local-dags-folder-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/anomp/dev/kube-local/airflow-kube-local/dags"